repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.11
    hooks:
      - id: ruff-format
        args: [--check]
      - id: ruff

  - repo: https://github.com/pre-commit/mirrors-pycodestyle
    rev: v2.12.1
    hooks:
      - id: pycodestyle
        args: [--ignore=E501, backend]
